name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest

